name: Deploy
on:
  push
jobs:
  build:
    name: Run Web App
    runs-on: ubuntu-latest

    env:
      GIT_COMMIT_HASH: ${GITHUB_REF##*/}

    steps:
      - name: Deploy Web App
        run: |
          echo "Deploy Web App"
          echo ${GITHUB_REF##*/}
      - name: print env
        run: |
          env
          hostname -f
          ifconfig
      - name: Build Web App
        run: |
          echo "Build Web App"
          curl -X POST \
          https://api.github.com/repos/raghavendra09/demobackend/actions/workflows/deploy.yml/dispatches \
          -H "Authorization: Bearer ${{ secrets.G_ACCESS_TOKEN }}" \
          -d '{"ref":"${{ github.ref }}"}'
